# Generated by Django 5.1.2 on 2024-12-11 01:30

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_moviereview'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
    ]
