# Generated by Django 5.1.2 on 2024-12-12 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_remove_movie_search_vector_favoritemovie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FavoriteMovie',
        ),
    ]
